from websocket import create_connection
# ws = create_connection("ws://echo.websocket.org/")
ws = create_connection("ws://130.215.219.68:9090/ws")
print("Sending 'Hello, World'...")
ws.send("Hello, World")
print("Sent")
print("Receiving...")
result =  ws.recv()
print("Received '%s'" % result)
ws.close()